### PR TITLE
feat: Added isEmpty() for Singly Linked List

### LINKED ISSUE #24: Implement `isEmpty()` function for a Singly Linked List
Taking reference from issue [#12](https://github.com/code-sherpas/kollections/issues/12), implement the `isEmpty()` function for a Singly Linked List. This function will check if the list is empty.

### First step
Search, read, and understand information about lists, linked lists, and singly-linked lists, and how they are implemented.

### Second step
Open a pull request with the data structure implementation, and wait for comments from @code-sherpas/kollections-maintainers.

### Minimum acceptance criteria
* The implementation must be well documented with proper Javadoc at Class and function levels.
* The implementation must be tested with automatic tests that cover all relevant cases and situations.
* The implementation must be generic.
* The implementation must have the expected time complexity according to Computer Science. [Here you can find a very helpful cheat sheet](https://www.bigocheatsheet.com/).

### Related resources:
* https://www.youtube.com/watch?v=v4cd1O4zkGw&ab_channel=HackerRank
* https://www.youtube.com/watch?v=njTh_OwMljA&ab_channel=HackerRank
* https://en.wikipedia.org/wiki/List_(abstract_data_type)
* https://en.wikipedia.org/wiki/Linked_list#Singly_linked_list
* https://www.bigocheatsheet.com/

### PR DESCRIPTION
**Pull request by bhaveesarna**
closes #24

### CODE REVIEW

**Comment by bhaveesarna** [comment]
Closes #24

**Comment by ashikka** [comment]
Great job @bhaveesarna! Could write a unit test for this function's implementation? 

Taking reference from this [dummy test](https://github.com/code-sherpas/kollections/blob/main/lib/src/test/kotlin/main/DummyTest.kt), implement the container tests for a Singly Linked List. 

### First step
Search, read, and understand information about lists, linked lists, and singly-linked lists, and how they are implemented.

### Second step
Open a pull request with the data structure implementation, and wait for comments from @code-sherpas/kollections-maintainers.

### Minimum acceptance criteria
* The implementation must be well documented with proper Javadoc at Class and function levels.
* The implementation must be tested with automatic tests that cover all relevant cases and situations.
* The implementation must be generic.
* The implementation must have the expected time complexity according to Computer Science. [Here you can find a very helpful cheat sheet](https://www.bigocheatsheet.com/).

### Related resources:
* https://medium.com/swlh/a-different-look-at-api-tests-with-rest-assured-junit-5-and-kotlin-590789f31097

**Comment by bhaveesarna** [comment]
@ashikka I've implemented a test case for the function

**Comment by ashikka** [comment]
Great job @bhaveesarna! I think we can merge this PR. Woohoo :tada:

**Pull request merged**
